### ISSUE TITLE
Add more topics and resources

### ISSUE THREAD

**Issue by PragatiVerma18** [NJACKWinterOfCode/learn-for-free#1]
Please add more topics, sub-topics, and resources to grow this list. Please make sure to read [CONTRIBUTING.md](https://github.com/aviaryan/learn-for-free/blob/master/CONTRIBUTING.md) before opening a pull request.

**Comment by sgpritam** [comment]
Please explain the codebase @PragatiVerma18

**Comment by PragatiVerma18** [comment]
This is a simple collection of free online resources related to various skills and fields listed out in separated markdown files of each field or domain. This project utilises basic GitHub flavoured markdown syntax.

**Comment by Sahastracookcoder1** [comment]
I would like to work on this issue

**Comment by sakshamj74** [comment]
can I add some cheat sheets related to data science

**Comment by PragatiVerma18** [comment]
Hi @sakshamj74!!! Go ahead but be sure that these online resources are free and easy to comprehend.

**Comment by sakshamj74** [comment]
hi @PragatiVerma18 should I give a link to resources like pdf's or upload them directly.

**Comment by PragatiVerma18** [comment]
@sakshamj74 please see the format in which the files are written, they are markdown files, you just have to add the free online resources you think are good for the individuals trying to learn something new with an image and a link to the website or webpage.

**Comment by vishal-bhola** [comment]
I have made PR and added some topics please review it @PragatiVerma18

**Comment by Tanmay211** [comment]
Hi @PragatiVerma18 ! I would like to add a new resouce as well. So can I contribute ?

**Comment by PragatiVerma18** [comment]
Yes please start contributing.

**Comment by vishal-bhola** [comment]
@PragatiVerma18  Please review my PR

**Comment by vishal-bhola** [comment]
@PragatiVerma18  resource for Natural Language Processing is added please review.

**Comment by Tanmay211** [comment]
@PragatiVerma18 Please review my PR and recommend any changes if needed. Please merge the resouce if you find it good.
Thanks!

**Comment by Tanmay211** [comment]
@PragatiVerma18 I made the changes that you asked me to make. So please review my PR once again.

**Comment by SREEHARI-M-S** [comment]
@PragatiVerma18 I have made a PR #39 and recommend any changes if needed. Please merge those design resources which I found very useful and if you think it is good. Thank you.

**Comment by ivaibhavjindal** [comment]
@PragatiVerma18 Hey! I'd like to add some resources to Programming Basics, Web development and Android. Can I?
