### ISSUE TITLE
Make a website to list out free learning resources.

### ISSUE THREAD

**Issue by PragatiVerma18** [NJACKWinterOfCode/learn-for-free#2]
Add a simple website using HTML, CSS and JS or preferably **using GitHub pages themes like Jekyll etc.** that lists out all the free resources available in this repo. Use embed tags or iframe tags to showcase an image/video of each resource listed here.

**Comment by shreyateeza** [comment]
I would like to work on this issue!

**Comment by PragatiVerma18** [comment]
@shreyateeza go ahead!! All the best.

**Comment by shreyateeza** [comment]
@PragatiVerma18  What is your twitter username?

**Comment by sk044** [comment]
I would like to work on this issue if you want or if anyone else is not working on it..

**Comment by PragatiVerma18** [comment]
This task has been completed by @shreyateeza. @sk044 you may try #19

**Comment by MahmoudMabrok** [comment]
what is link for website? @PragatiVerma18 , where source code to modify and add contribution page

**Comment by PragatiVerma18** [comment]
You have to add contributor's page to the repo in the form of a markdown file or either inside the readme.md. The link for the website is here: <a href="https://pragativerma18.github.io/learn-for-free/">https://pragativerma18.github.io/learn-for-free/</a>

**Comment by MahmoudMabrok** [comment]
if it finished could you close this issue?

**Comment by PragatiVerma18** [comment]
I would like to have some improvements in the UI if possible and also fix the unclickable links if possible.

**Comment by MahmoudMabrok** [comment]
i will try to fix unclickable links @PragatiVerma18
