### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by verkiya** [NJACKWinterOfCode/learn-for-free#31]
Please correct the **spelling** of the resource mentioned in the screenshot below.

![spelling mistake](https://user-images.githubusercontent.com/34170205/70368917-00e0f700-18d7-11ea-8047-f96022d9f840.png)

Hack This Time is mentioned instead of Hack This Site in the description of the resource.

**Comment by harsh7in** [comment]
i would like to work on this issue
