### ISSUE TITLE
links in website not clickable

### ISSUE THREAD

**Issue by MahmoudMabrok** [NJACKWinterOfCode/learn-for-free#47]
links in website **not clickable** it should be clickable and link to outside site.

**Comment by PragatiVerma18** [comment]
All links on the website are working. Please clarify your problem through screenshots if possible with proper annotation.

**Comment by MahmoudMabrok** [comment]
![Screenshot from 2020-01-03 15-31-03](https://user-images.githubusercontent.com/13488900/71725921-33cacc00-2e3e-11ea-9301-c704f78869e7.png)


here `Website - https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi` should be clicked


i am sorry for not clear description 

i did mean links to resources such as websites, youtube, ....etc

**Comment by PragatiVerma18** [comment]
Okay, so can you fix this? If you are interested to fix this, please try to send a PR to fix this. 😀

**Comment by MahmoudMabrok** [comment]
i will try with it @PragatiVerma18
